# Generated by Django 3.2.4 on 2021-06-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_user_user_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Technical_Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('experience_level', models.IntegerField(default='on the scale of 100')),
            ],
        ),
    ]
