# Generated by Django 3.2.4 on 2021-06-29 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_technical_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technical_skills',
            name='experience_level',
            field=models.IntegerField(),
        ),
    ]
