# Generated by Django 3.2.4 on 2021-06-29 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_rename_technical_skills_technical_skill'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Testimonails',
            new_name='Testimonail',
        ),
    ]
