# Generated by Django 3.2.4 on 2021-07-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Testimonail',
        ),
        migrations.DeleteModel(
            name='User',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
